### ISSUE TITLE
Feature Request: embedded content visualization

### ISSUE THREAD

**Issue by goldkin** [edent/TweeView#17]
Copypasta from my tweet reply yesterday:

* It'd be really cool to see breakdown of embedded content, RT, quote RT, image, link, multimedia.

This was posted in response to a request for suggestions.

To describe further, it would be useful to see a thumbnail or UI hint by each avatar in the discussion describing its _type_ of embedded content (canonical RT symbol by a retweet, RT with ellipsis for quote RT, w3c loading image for image, etc), since these data are made available to the Twitter API.

Some parsing of t.co URLs _may_ be necessary to figure out the type of media content -- but this functionality appears to exist in other Twitter parsing packages like within Bitlbee. This parsing seems possible.

The purpose of this would be to visualize not just the tree view of content, but make it possible to reason about its bias towards certain types of media from discussion to discussion. This seems like a useful addition to the tool that is still digestible "at a glance".

No code submitted for now (employer contractual obligations, sorry!). However, being able to drop the feature idea here is entirely fair game. Good luck!

**Comment by edent** [comment]
I've added in RT and FAV count
![favrt](https://cloud.githubusercontent.com/assets/837136/24285025/21d11f2a-1066-11e7-86d7-f225cdc5436e.png)

When clicking on a tweet - it will (eventually) display the embedded media, links etc.

**Comment by edent** [comment]
Added some stokes to make things clearer.
![rtfav count](https://cloud.githubusercontent.com/assets/837136/24315473/1c3c8f9e-10df-11e7-97c0-4ddfd40c91b9.png)
