### ISSUE TITLE
Web Site DNS expired?

### ISSUE THREAD

**Issue by jimmy6DOF** [edent/TweeView#22]
tweeview.ml is now doing a sketchy re-direct to http://freenom.link/?k=80808080&_=1661508040 

Hope you re-implement this in Aframe or Babylon or similar in a version 2.0+ with a Z-axis !

**Comment by edent** [comment]
Looks like Freenom have taken back the domain. If you know of another free domain name provider, I can rehost it.

I do have a 3D version. You can see a demo at https://shkspr.mobi/blog/2021/09/visualising-twitter-conversations-in-3d-space/

**Comment by edent** [comment]
Freenom have graciously restored it. Should be working now.
